CREATE TABLE IF NOT EXISTS ACCOUNT(
    id BIGINT PRIMARY KEY,
    ACCOUNT VARCHAR(250) NOT NULL,
    PASSWORD VARCHAR(250) NOT NULL
);

CREATE TABLE IF NOT EXISTS CC_Orders(
    id BIGINT PRIMARY KEY,
    ACCOUNT VARCHAR(250) NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE INT NOT NULL,
    ACTION VARCHAR(250)
);